"""
nTron electrothermal device model.

Direct Python port of `ntron_2.lib` (Berggren-group style hotspot model,
as used in the spiking_transponder_circuit LTspice project).

The device is a 3-terminal nanocryotron: gate (g), drain (d), source (s),
meeting at an internal node `center`.  Each terminal branch carries a
current-dependent kinetic inductance in series with a hotspot resistance
that is generated by a growth ODE once the branch goes normal.

Branch structure (mirrors the .lib exactly)
-------------------------------------------
    gate    : g --[Lg]-- N1   --[r_g]-------------------- center
    source  : s --[Ls]-- N01c --[Lc1]-- N01 --[r_c_s + r_s]-- center
    drain   : d --[Ld]-- N100 --[Lc2]-- N001 --[r_c_d + r_d]-- center

Because Lg/Ls/Lc1 and Ld/Lc2 are in series with no intervening branch,
each terminal path collapses to a single lumped inductor + a single
lumped hotspot resistance:

    L_gate   = Lind_g
    L_source = Lind_s + Lind_c/2      R_source = max(r_c_s,0) + max(r_s,0)
    L_drain  = Lind_d + Lind_c/2      R_drain  = max(r_c_d,0) + max(r_d,0)

so the device presents exactly three branches to the external circuit.

Hotspot state variables (5)
---------------------------
    r_g    gate hotspot                    -> Rnorm_g
    r_c_s  source-side channel half        -> Rnorm_c/2
    r_s    source segment                  -> Rnorm_s   (only after r_c_s saturates)
    r_c_d  drain-side channel half         -> Rnorm_c/2
    r_d    drain segment                   -> Rnorm_d   (only after r_c_d saturates)

The gate->channel gain is the `Bc_s` source in the .lib: once the gate
current exceeds Isw_g, the channel critical current is suppressed by
`A1 * exp(-(|I_g| - Isw_g)/beta)`, which is what makes the nTron an
amplifier rather than just a switch.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

# ---------------------------------------------------------------------------
# Fixed constants from the .lib header
# ---------------------------------------------------------------------------
HEAT_CAPACITY = 4400.0     # J / m^3 / K
H_C = 50e3                 # surface thermal conductance, W / m^2 / K
LORENZ = 2.44e-8           # Wiedemann-Franz Lorenz number
INDUCTIVITY_COEF = 1.38e-12   # H/sq per (ohm/sq / K)
DELTA = 0.01               # regulariser in the hotspot velocity expression


@dataclass
class NTronParams:
    """Geometry / material parameters for one nTron (`.subckt ntron_r` params)."""

    width_g: float = 20e-9
    width_s: float = 200e-9
    width_d: float = 200e-9
    width_c: float = 250e-9

    sq_g: float = 5.0
    sq_d: float = 400.0
    sq_s: float = 80.0
    sq_c: float = 10.0

    thickness: float = 19e-9
    sheetRes: float = 130.0     # ohm/sq
    Tc: float = 8.5             # K
    Tsub: float = 4.3           # K
    Jc: float = 40e9            # A/m^2 at Tsub
    C: float = 1.0              # constriction factor
    A1: float = 0.4             # gate-gain prefactor
    beta: float = 12.82e-6      # gate-gain current scale (A)

    # ---- derived, filled in __post_init__ -------------------------------
    Isw_g: float = field(init=False)
    Isw_d: float = field(init=False)
    Isw_s: float = field(init=False)
    Isw_c: float = field(init=False)
    Rnorm_g: float = field(init=False)
    Rnorm_d: float = field(init=False)
    Rnorm_s: float = field(init=False)
    Rnorm_c: float = field(init=False)
    Lind_g: float = field(init=False)
    Lind_d: float = field(init=False)
    Lind_s: float = field(init=False)
    Lind_c: float = field(init=False)
    psi: float = field(init=False)
    vo: float = field(init=False)
    kappa: float = field(init=False)
    Vthresh_g: float = field(init=False)
    Vthresh_s: float = field(init=False)
    Vthresh_c: float = field(init=False)
    C_hs_g: float = field(init=False)
    C_hs_s: float = field(init=False)
    C_hs_d: float = field(init=False)
    C_hs_c: float = field(init=False)

    def __post_init__(self) -> None:
        p = self
        jt = p.Jc * p.thickness

        # Critical (switching) currents: Isw = Jc * w * t * C
        p.Isw_g = p.Jc * p.width_g * p.thickness * p.C
        p.Isw_d = p.Jc * p.width_d * p.thickness * p.C
        p.Isw_s = p.Jc * p.width_s * p.thickness * p.C
        p.Isw_c = p.Jc * p.width_c * p.thickness * p.C

        # Normal-state resistances
        p.Rnorm_g = p.sheetRes * p.sq_g
        p.Rnorm_d = p.sheetRes * p.sq_d
        p.Rnorm_s = p.sheetRes * p.sq_s
        p.Rnorm_c = p.sheetRes * p.sq_c

        # Kinetic inductance
        inductivity = INDUCTIVITY_COEF * p.sheetRes / p.Tc      # H/sq
        p.Lind_g = inductivity * p.sq_g
        p.Lind_d = inductivity * p.sq_d
        p.Lind_s = inductivity * p.sq_s
        p.Lind_c = inductivity * p.sq_c

        # Thermal
        p.kappa = LORENZ * p.Tc / (p.sheetRes * p.thickness)
        p.psi = p.sheetRes * jt**2 / (H_C * (p.Tc - p.Tsub))     # Stekly parameter
        p.vo = math.sqrt(H_C * p.kappa / p.thickness) / HEAT_CAPACITY

        # Retrapping ("hotspot") currents and the voltage criterion.
        # minSquares*sheetRes == 1, so Vthresh is numerically equal to Ihs.
        sq2psi = math.sqrt(2.0 / p.psi)
        p.Vthresh_g = sq2psi * p.Isw_g
        p.Vthresh_s = sq2psi * p.Isw_s
        p.Vthresh_c = sq2psi * p.Isw_c

        # Hotspot-growth integrator capacitances: C = width / (sheetRes * vo)
        p.C_hs_g = p.width_g / (p.sheetRes * p.vo)
        p.C_hs_s = p.width_s / (p.sheetRes * p.vo)
        p.C_hs_d = p.width_d / (p.sheetRes * p.vo)
        p.C_hs_c = p.width_c / (p.sheetRes * p.vo)

    # -- convenience ------------------------------------------------------
    @property
    def Ihs_g(self) -> float:
        """Gate retrapping current: hotspot shrinks below this."""
        return math.sqrt(2.0 / self.psi) * self.Isw_g

    def summary(self) -> str:
        return (
            f"Isw_g={self.Isw_g*1e6:8.3f} uA   Isw_c={self.Isw_c*1e6:8.3f} uA   "
            f"Isw_d={self.Isw_d*1e6:8.3f} uA   Isw_s={self.Isw_s*1e6:8.3f} uA\n"
            f"Rn_g ={self.Rnorm_g:8.1f} R    Rn_c ={self.Rnorm_c:8.1f} R    "
            f"Rn_d ={self.Rnorm_d:8.1f} R    Rn_s ={self.Rnorm_s:8.1f} R\n"
            f"L_g  ={self.Lind_g*1e12:8.2f} pH   L_c  ={self.Lind_c*1e12:8.2f} pH   "
            f"L_d  ={self.Lind_d*1e12:8.2f} pH   L_s  ={self.Lind_s*1e12:8.2f} pH\n"
            f"psi  ={self.psi:8.2f}      vo   ={self.vo:8.2f} m/s  "
            f"Ihs_g={self.Ihs_g*1e6:7.4f} uA"
        )


# ---------------------------------------------------------------------------
# Shared nonlinear functions
# ---------------------------------------------------------------------------
def hotspot_velocity(I: float, Isw: float, psi: float) -> float:
    """
    Normalised S/N boundary velocity, i.e. the `B3`/`B03`/`B003` expression:

        f(I) = (psi*(I/Isw)^2 - 2) / ( sqrt(max(psi*(I/Isw)^2 - 1, 0)) + delta )

    Positive -> hotspot grows, negative -> hotspot shrinks (retrapping).
    dr/dt = f(I) / C_hs.
    """
    q = psi * (I / Isw) ** 2
    return (q - 2.0) / (math.sqrt(max(q - 1.0, 0.0)) + DELTA)


def kinetic_L(I: float, Isw: float, Lind: float, r: float, Rnorm: float) -> float:
    """
    Incremental kinetic inductance dPhi/dI for the `Flux=` inductors in the .lib:

        Phi(I) = A(r) * Lind * I / (2*cos((2/3)*asin(0.6*|I|/Isw)) - 1)
        A(r)   = 1 - r/Rnorm + 0.001

    A(r) makes the kinetic inductance collapse as the wire goes normal.
    Returned value is the *incremental* inductance at fixed r; the
    (small) dPhi/dr cross-term is neglected, as is standard practice.
    """
    A = max(1.0 - max(r, 0.0) / Rnorm + 0.001, 1e-3)
    u = min(0.6 * abs(I) / Isw, 0.999)
    theta = (2.0 / 3.0) * math.asin(u)
    ct, st = math.cos(theta), math.sin(theta)
    den = 2.0 * ct - 1.0
    g = 1.0 / den
    # d(g*I)/dI = g + |I| * dg/d|I|
    dtheta_du = (2.0 / 3.0) / math.sqrt(max(1.0 - u * u, 1e-9))
    du_dabsI = 0.6 / Isw
    dg_dabsI = 2.0 * st / (den * den) * dtheta_du * du_dabsI
    return A * Lind * (g + abs(I) * dg_dabsI)


# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------
class NTron:
    """
    One nTron.  Presents three branches (gate/drain/source) to the circuit
    engine, all meeting at a private internal node.

    State
    -----
    I_g, I_d, I_s : branch currents, defined positive *into* the device
                    from the terminal toward `center`.
    r_g, r_c_s, r_s, r_c_d, r_d : hotspot resistances (may go slightly
                    negative during retrapping, clamped at use).
    """

    N_HOTSPOT = 5

    def __init__(self, name: str, params: NTronParams,
                 reset_segment_hotspots: bool = True):
        self.name = name
        self.p = params
        # The source-side `S02` switch is absent in ntron_2.lib (only a 100 GR
        # bleed resistor), so r_s never resets there.  That is almost certainly
        # a typo in the .lib -- the drain side has both S001 and S002.  Default
        # to the symmetric (drain-like) behaviour; set False for bug-compatible.
        self.reset_segment_hotspots = reset_segment_hotspots

        self.I_g = 0.0
        self.I_d = 0.0
        self.I_s = 0.0
        self.r_g = 0.0
        self.r_c_s = 0.0
        self.r_s = 0.0
        self.r_c_d = 0.0
        self.r_d = 0.0

        self.normal_g = False
        self.normal_s = False
        self.normal_d = False

    # -- gate gain --------------------------------------------------------
    def channel_ic_factor(self) -> float:
        """`Bc_s`: multiplicative suppression of the channel critical current."""
        p = self.p
        ag = abs(self.I_g)
        if ag > p.Isw_g:
            return p.A1 * math.exp(-(ag - p.Isw_g) / p.beta)
        return 1.0

    # -- lumped branch R / L ---------------------------------------------
    def branch_R(self) -> tuple[float, float, float]:
        """(R_gate, R_drain, R_source) hotspot resistance seen by the circuit."""
        return (
            max(self.r_g, 0.0),
            max(self.r_c_d, 0.0) + max(self.r_d, 0.0),
            max(self.r_c_s, 0.0) + max(self.r_s, 0.0),
        )

    def branch_L(self) -> tuple[float, float, float]:
        """(L_gate, L_drain, L_source) incremental kinetic inductance."""
        p = self.p
        Lg = kinetic_L(self.I_g, p.Isw_g, p.Lind_g, self.r_g, p.Rnorm_g)
        Ld = (kinetic_L(self.I_d, p.Isw_d, p.Lind_d, self.r_d, p.Rnorm_d)
              + kinetic_L(self.I_d, p.Isw_c, p.Lind_c / 2, self.r_c_d, p.Rnorm_c / 2))
        Ls = (kinetic_L(self.I_s, p.Isw_s, p.Lind_s, self.r_s, p.Rnorm_s)
              + kinetic_L(self.I_s, p.Isw_c, p.Lind_c / 2, self.r_c_s, p.Rnorm_c / 2))
        return Lg, Ld, Ls

    # -- latches (`B2`, `B02`, `B002`) ------------------------------------
    def update_latches(self) -> None:
        p = self.p
        m = self.channel_ic_factor()
        Rg, Rd, Rs = self.branch_R()

        self.normal_g = (abs(self.I_g) > p.Isw_g) or (Rg * abs(self.I_g) > p.Vthresh_g)
        self.normal_s = (abs(self.I_s) > p.Isw_c * m) or (Rs * abs(self.I_s) > p.Vthresh_c)
        self.normal_d = (abs(self.I_d) > p.Isw_c * m) or (Rd * abs(self.I_d) > p.Vthresh_c)

    # -- hotspot integration (`B3`, `B03`/`B04`, `B003`/`B004`) -----------
    def step_hotspots(self, h: float) -> None:
        p = self.p

        # --- gate ---
        if self.normal_g:
            if self.r_g < p.Rnorm_g:
                self.r_g += h * hotspot_velocity(self.I_g, p.Isw_g, p.psi) / p.C_hs_g
                self.r_g = min(self.r_g, p.Rnorm_g)
        else:
            self.r_g = 0.0

        # --- source side: channel half first, then the source segment ---
        if self.normal_s:
            half = p.Rnorm_c / 2
            if self.r_c_s <= half:
                self.r_c_s += h * hotspot_velocity(self.I_s, p.Isw_c, p.psi) / p.C_hs_c
                self.r_c_s = min(self.r_c_s, half)
            elif self.r_s < p.Rnorm_s:
                self.r_s += h * hotspot_velocity(self.I_s, p.Isw_s, p.psi) / p.C_hs_s
                self.r_s = min(self.r_s, p.Rnorm_s)
        else:
            self.r_c_s = 0.0
            if self.reset_segment_hotspots:
                self.r_s = 0.0

        # --- drain side ---
        if self.normal_d:
            half = p.Rnorm_c / 2
            if self.r_c_d <= half:
                self.r_c_d += h * hotspot_velocity(self.I_d, p.Isw_c, p.psi) / p.C_hs_c
                self.r_c_d = min(self.r_c_d, half)
            elif self.r_d < p.Rnorm_d:
                self.r_d += h * hotspot_velocity(self.I_d, p.Isw_d, p.psi) / p.C_hs_d
                self.r_d = min(self.r_d, p.Rnorm_d)
        else:
            self.r_c_d = 0.0
            self.r_d = 0.0

    # -- diagnostics ------------------------------------------------------
    @property
    def is_switched(self) -> bool:
        """True while the drain-source channel is carrying a hotspot."""
        return self.normal_d or self.normal_s

    def max_dr_dt(self) -> float:
        """Fastest hotspot growth rate right now -- used for step control."""
        p = self.p
        rate = 0.0
        if self.normal_g:
            rate = max(rate, abs(hotspot_velocity(self.I_g, p.Isw_g, p.psi)) / p.C_hs_g)
        if self.normal_d:
            rate = max(rate, abs(hotspot_velocity(self.I_d, p.Isw_c, p.psi)) / p.C_hs_c)
        if self.normal_s:
            rate = max(rate, abs(hotspot_velocity(self.I_s, p.Isw_c, p.psi)) / p.C_hs_c)
        return rate
